AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Express Application/API powered by API Gateway and Lambda
Parameters:
  DomainName:
    Type: String
    Description: API Domain name
    Default: ''
Conditions:
  UseDomainName:
    Fn::Not:
    - Fn::Equals:
      - Ref: DomainName
      - ''
Resources:
  ExpressApi:
    Type: AWS::Serverless::HttpApi
  ExpressLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://cookieshaking-image-repo/cc827fbbc41ea066ca09d56d75197335
      Handler: main.handler
      MemorySize: 1024
      Runtime: nodejs12.x
      Timeout: 30
      Events:
        ProxyApiRoot:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: ExpressApi
  MyApiDomainName:
    Type: AWS::ApiGateway2::DomainName
    Condition: UseDomainName
    Properties:
      CertificateArn: arn:aws:acm:us-east-1:253965625087:certificate/015f99b1-4d59-4549-a230-49bae9c82fe4
      DomainName:
        Ref: DomainName
  MyApiBasePathMapping:
    Type: AWS::ApiGateway2::BasePathMapping
    Condition: UseDomainName
    Properties:
      RestApiId:
        Ref: ExpressApi
      DomainName:
        Ref: MyApiDomainName
      BasePath: (none)
      Stage: prod
  MyApiRoute53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Condition: UseDomainName
    Properties:
      HostedZoneId: Z073823926JI5KKWB37CQ
      RecordSets:
      - Name:
          Fn::Sub: ${DomainName}.
        Type: A
        AliasTarget:
          EvaluateTargetHealth: false
          HostedZoneId:
            Fn::GetAtt:
            - MyApiDomainName
            - DistributionHostedZoneId
          DNSName:
            Fn::GetAtt:
            - MyApiDomainName
            - DistributionDomainName
      - Name:
          Fn::Sub: www.${DomainName}.
        Type: A
        AliasTarget:
          EvaluateTargetHealth: false
          HostedZoneId:
            Fn::GetAtt:
            - MyApiDomainName
            - DistributionHostedZoneId
          DNSName:
            Fn::GetAtt:
            - MyApiDomainName
            - DistributionDomainName
Outputs:
  LambdaFunctionConsoleUrl:
    Description: Console URL for the Lambda Function.
    Value:
      Fn::Sub: https://${AWS::Region}.console.aws.amazon.com/lambda/home?region=${AWS::Region}#/functions/${ExpressLambdaFunction}
  ApiGatewayApiConsoleUrl:
    Description: Console URL for the API Gateway API's Stage.
    Value:
      Fn::Sub: https://${AWS::Region}.console.aws.amazon.com/apigateway/home?region=${AWS::Region}#/apis/${ExpressApi}/stages/prod
  ApiUrl:
    Description: Invoke URL for your API. Clicking this link will perform a GET request
      on the root resource of your API.
    Value:
      Fn::Sub: https://${ExpressApi}.execute-api.${AWS::Region}.amazonaws.com/
  LambdaFunctionName:
    Description: Name of the Serverless Express Lambda Function
    Value:
      Ref: ExpressLambdaFunction
